refactor complete

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -4,18 +4,79 @@
 #
 # `dot` handles installation, updates, things like that. Run it periodically
 # to make sure you're on the latest and greatest.
-export ZSH=$HOME/.dotfiles
 
-# Set macOS defaults
-$ZSH/macos/set-defaults.sh
+set -e
+
+parentDirectory="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
+dotfilesDirectory="$(cd "$( dirname "$parentDirectory" )" && pwd -P)"
+
+displayUsageAndExit() {
+    echo "dot -- dotfiles management"
+    echo ""
+    echo "Usage: dot [options]"
+    echo ""
+    echo "Options:"
+    echo "  -e, --edit    Open dotfiles directory for editing"
+    echo "  -h, --help    Show this help message and exit"
+    echo "  update        Update packages and pkg managers"
+    exit
+}
+
+while test $# -gt 0; do
+    case "$1" in
+        "-h"|"--help")
+            displayUsageAndExit
+            ;;
+        "-e"|"--edit")
+            exec code "$dotfilesDirectory"
+            exit
+            ;;
+        "update")
+            if [ "$(uname -s)" = "Darwin" ]; then
+                # Update Homebrew
+                echo "› brew update"
+                brew update
+                echo "› brew upgrade"
+                brew upgrade
+                echo "› brew cleanup"
+                brew cleanup
+            fi
+
+            # Update Oh My Zsh
+            echo "› updating oh-my-zsh"
+            /bin/sh $ZSH/tools/upgrade.sh
+
+            # Update dotfiles
+            echo "› git pull origin master"
+            cd "$dotfilesDirectory" || exit
+            git pull origin master
+
+            # Update all VS Code extensions
+            echo "› updating VS Code extensions"
+            code --list-extensions | xargs -L 1 code --install-extension
+            if command -v code-insiders &> /dev/null; then
+                code-insiders --list-extensions | xargs -L 1 code-insiders --install-extension
+            fi
+
+            exit
+            ;;
+        *)
+            echo "Invalid option: $1"
+            displayUsageAndExit
+            ;;
+    esac
+    shift
+done
+
+export ZSH=$HOME/.oh-my-zsh
 
 # Install homebrew
-$ZSH/homebrew/install.sh 2>&1
+$dotfilesDirectory/homebrew/install.sh 2>&1
 
 # Upgrade homebrew
 echo "› brew update"
 brew update
 
 # Install software
-echo "› $ZSH/script/install"
-$ZSH/script/install
+echo "› $dotfilesDirectory/script/install"
+$dotfilesDirectory/script/install
